### ISSUE TITLE
Cannot find module './adapters/sequelize'

### ISSUE THREAD

**Issue by qinsJs** [hzeyuan/egg-oidc-demo#1]
我运用您的Demo，遇见了这个问题。

```sh
2021-09-24 16:01:00,548 ERROR 28718 database connect error ==> Error: Cannot find module './adapters/sequelize'
Require stack:
- /Users/qins/Documents/projects/hy/egg-oidc-demo/app.ts
- /Users/qins/Documents/projects/hy/egg-oidc-demo/node_modules/egg-core/lib/utils/index.js
- /Users/qins/Documents/projects/hy/egg-oidc-demo/node_modules/egg-core/lib/egg.js
- /Users/qins/Documents/projects/hy/egg-oidc-demo/node_modules/egg-core/index.js
- /Users/qins/Documents/projects/hy/egg-oidc-demo/node_modules/egg/lib/application.js
- /Users/qins/Documents/projects/hy/egg-oidc-demo/node_modules/egg/index.js
- /Users/qins/Documents/projects/hy/egg-oidc-demo/node_modules/egg-cluster/lib/app_worker.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:889:15)
    at Function.Module._load (internal/modules/cjs/loader.js:745:27)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at AppBootHook.<anonymous> (/Users/qins/Documents/projects/hy/egg-oidc-demo/app.ts:45:17)
    at Generator.next (<anonymous>)
    at /Users/qins/Documents/projects/hy/egg-oidc-demo/node_modules/tslib/tslib.js:115:75
    at new Promise (<anonymous>)
    at Object.__awaiter (/Users/qins/Documents/projects/hy/egg-oidc-demo/node_modules/tslib/tslib.js:111:16)
    at AppBootHook.willReady (/Users/qins/Documents/projects/hy/egg-oidc-demo/app.ts:24:24) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/qins/Documents/projects/hy/egg-oidc-demo/app.ts',
    '/Users/qins/Documents/projects/hy/egg-oidc-demo/node_modules/egg-core/lib/utils/index.js',
    '/Users/qins/Documents/projects/hy/egg-oidc-demo/node_modules/egg-core/lib/egg.js',
    '/Users/qins/Documents/projects/hy/egg-oidc-demo/node_modules/egg-core/index.js',
    '/Users/qins/Documents/projects/hy/egg-oidc-demo/node_modules/egg/lib/application.js',
    '/Users/qins/Documents/projects/hy/egg-oidc-demo/node_modules/egg/index.js',
    '/Users/qins/Documents/projects/hy/egg-oidc-demo/node_modules/egg-cluster/lib/app_worker.js'
  ]
}
```

我想请教一下，`./adapters/` 的 `sequelize` 是需要自己编写吗？

能不能指点指点

**Comment by hzeyuan** [comment]
async willReady() {
const { app } = this;
// 加载自定义
// const adapter = new MyAdapter('test');
const configuration = app.config.oidcProvider || {};
const PORT = '7001';
const ISSUER = `http://localhost:${PORT}`;
app.logger.info('[egg-oidc-provider] oidc-provider begin start');
app.use(helmet());
// 所有的插件都已启动完毕，但是应用整体还未 ready
// 可以做一些数据初始化等操作，这些操作成功才会启动应用
// adapter: MyAdapter,
let adapter;
try {
adapter = require('./adapters/sequelize');
await adapter.connect();
} catch (e) {
app.logger.error('database connect error ==>', e);
}
const provider = new Provider(ISSUER, { ...configuration, adapter });
// await provider.initialize({ adapter: SequelizeAdapter });
// const c = provider.clientAdd({
// client_id: '2',
// client_secret: '2',
// grant_types: [ 'refresh_token', 'authorization_code' ],
// redirect_uris: [ 'http://127.0.0.1:5500/app/view/app1.html', '
http://127.0.0.1:5500/app/view/app2.html' ],
// });
// console.log('provider.Client', c);
provider.use(helmet());
app.oidcProvider = provider;
app.use(mount('/', provider.app));
// 例如：从数据库加载数据到内存缓存
}
在那个app.ts里面有配置连接数据库的，具体我也记不太清了

>
